import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	loader: {
		'.ts': 'ts'
	},
	resolveExtensions: ['.ts', '.js'],
	tsconfig: './tsconfig.json'
});

// Deploy built files to test vault
const TEST_VAULT_PLUGIN_DIR = join(
	process.env.HOME || "",
	"vaults/test/.obsidian/plugins/naver-blog-importer"
);

function deployToTestVault() {
	if (!existsSync(TEST_VAULT_PLUGIN_DIR)) {
		mkdirSync(TEST_VAULT_PLUGIN_DIR, { recursive: true });
	}
	const files = ["main.js", "manifest.json", "styles.css"];
	for (const file of files) {
		if (existsSync(file)) {
			copyFileSync(file, join(TEST_VAULT_PLUGIN_DIR, file));
		}
	}
	console.log(`\x1b[32m✓ Deployed to ${TEST_VAULT_PLUGIN_DIR}\x1b[0m`);
}

if (prod) {
	await context.rebuild();
	deployToTestVault();
	process.exit(0);
} else {
	await context.watch();
}